name: pynetcf
dependencies:
- curl=7.45.0=0
- hdf5=1.8.15.1=2
- libnetcdf=4.3.3.1=3
- mkl=11.3.3=0
- netcdf4=1.2.2=np111py27_0
- numpy=1.11.0=py27_1
- openssl=1.0.2e=0
- pandas=0.19.1=np111py27_0
- pip=8.0.1=py27_0
- proj4
- py=1.4.31=py27_0
- pyflakes=1.1.0=py27_0
- pyproj
- pytest=2.9.1=py27_0
- python=2.7.11=0
- python-dateutil=2.5.3=py27_0
- pytz=2016.4=py27_0
- readline=6.2=2
- setuptools=19.4=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.26.0=py27_1
- zlib=1.2.8=0
- pip:
  - autopep8==1.2.2
  - backports.shutil-get-terminal-size==1.0.0
  - coverage==4.1
  - decorator==4.0.9
  - ipdb==0.10.0
  - ipython==4.2.0
  - ipython-genutils==0.1.0
  - pathlib2==2.1.0
  - pep8==1.7.0
  - pexpect==4.1.0
  - pickleshare==0.7.2
  - ptyprocess==0.5.1
  - pygeobase==0.3.9
  - pygeogrids==0.1.9
  - pykdtree==1.1.1
  - pytest-cov==2.2.1
  - simplegeneric==0.8.1
  - traitlets==4.2.1

