name: windows

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *' # daily

jobs:
  build:
    name: Build py${{ matrix.python-version }} @ ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.12']
        os: ['windows-latest']

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - name: Checkout Testdata
        shell: bash -l {0}
        run : |
          git submodule init
          git submodule update
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: pynetcf
          auto-activate-base: false
      - name: Print environment infos
        shell: bash -l {0}
        run: |
          conda info -a
          conda list
          pip list
          which pip
          which python
      - name: Install package and test
        shell: bash -l {0}
        run: |
          pip install -e .[testing]
          pytest --cache-clear
